apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  claimRef:
    namespace: default
    name: {{ .Release.Name }}-nextcloud-nextcloud
  hostPath:
    path: /data/nextcloud
    type: DirectoryOrCreate