apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.solidtime.Name }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.solidtime.Name }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: {{ .Values.solidtime.port }}
      protocol: TCP
      name: http
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: gotenberg
  selector:
    app: {{ .Release.Name }}-{{ .Values.solidtime.Name }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Values.solidtime.Name }}
  annotations:
    spec.ingressClassName: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
spec:
  tls:
  - secretName: {{ .Values.solidtime.Name }}-tls
    hosts:
      - {{ .Values.solidtime.host }}
  rules:
  - host: {{ .Values.solidtime.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-{{ .Values.solidtime.Name }}
            port:
              name: http