apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
spec:
  redirectScheme:
    scheme: https
    port: "8443" # This is my custom port where Traefik listens for HTTPS traffic
    permanent: true
