apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.evolution_api.Name }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.evolution_api.Name }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: {{ .Values.evolution_api.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-{{ .Values.evolution_api.Name }}
